name: veggie_seasons_v2
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-72.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  function_tree: ^0.9.0
  gap: ^3.0.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.0
  widgetbook: ^3.1.0
  widgetbook_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  widgetbook_generator: ^3.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
